version: '3.9'
services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend/src:/data
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
  backend:
    build: ./backend
    volumes:
      - ./backend/src:/data
    depends_on:
      - db
  db:
    build: ./db
    ports:
      - "3306:3306"
    volumes:
      - mysql-vol:/var/lib/mysql
  frontend:
    container_name: "frontend"
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    working_dir: /app
    ports:
      - 8000:8000
    environment:
      # - WDS_SOCKET_HOST=127.0.0.1 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/dist
    tty: true
volumes:
  mysql-vol: