version: '3.9'
services:
  nginx:
      build: ./nginx
      ports:
        - "80:80"
      depends_on:
        - backend
  backend:
    build: ./backend
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
  db:
    build: ./db
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
  frontend:
    container_name: "uts-frontend"
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    working_dir: /app
    ports:
      - 8080:8080
    environment:
      # - WDS_SOCKET_HOST=127.0.0.1 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/dist
    tty: true