version: '3.9'
services:
  frontend:
    container_name: "uts-fr"
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    working_dir: /app
    ports:
      - 8080:8080
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/dist
    tty: true