version: '3.9'
services:
  nginx:
    build: ./nginx
    ports:
      - '8080:80'
    volumes:
      - ./backend/src:/data
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
  backend:
    build: ./backend
    volumes:
      - ./backend/src:/data
    ports:
      - :9000 # this container is only reachable internally by other containers through the port 9000
    depends_on:
      - db
  db:
    build: ./db
    ports:
      - '3306:3306'
    volumes:
      - mysql-vol:/var/lib/mysql
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    working_dir: /app
    ports:
      - 8000:8000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/dist
    tty: true
    depends_on:
      - backend

volumes:
  mysql-vol:
